title: "My portfolio"
author: "Seok Lee"
description: "a blog about self-driving car"
lang: "en"

remote_theme: niklasbuschmann/contrast


# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
paginate: 2                 # use "layout: paginate" in the index.html to enable pagination

# Theme settings
hide_title: false            # remove site heading in the header
hide_footer: false           # hide the "previous" and "next" links at the end of each post
dark_theme: true            # use the dark mode as default
dark_header: false           # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - index.html
  - README.md
  - archive.md
#  - title: "https://"       # linking external sites is also supported

icons:                       # (optional) fontawesome icons in the header
  envelope: "mailto:seokleeuk@gmail.com"
  github: "https://github.com/seokleeus"
  linkedin: "https://linkedin.com/in/seoklee"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
 - jekyll-remote-theme

theme: jekyll-theme-modernist
